---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflows-secrets
  annotations:
    workflows.argoproj.io/description: |
      Minimum permissions needed for Argo Workflows to run Workflow specs
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflows-workflow
  annotations:
    workflows.argoproj.io/description: |
      Minimum permissions needed for Argo Workflows to run Workflow specs
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - ''
    resources:
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
      - 'apps'
      - 'batch'
    resources:
      - pods/exec
      - jobs
    verbs:
      - get
      - watch
      - list
      - create
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - get
      - list
      - watch
      - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflows-agent
  annotations:
    workflows.argoproj.io/description: |
      This is the minimum recommended permissions needed if you want to use the agent, e.g. for HTTP or plugin templates.
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets
    verbs:
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets/status
    verbs:
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflows-view-extras
rules:
- apiGroups:
    - argoproj.io
  resources:
    - eventsources
    - sensors
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - argoproj.io
  resources:
    - workflows
  verbs:
    - patch
    - delete
- apiGroups:
    - dataflow.argoproj.io
  resources:
    - pipelines
  verbs:
    - get
    - list
    - watch