apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-workflows
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflowtemplates
  - workfloweventbindings
  - cronworkflows
  - eventsources
  - sensors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dataflow.argoproj.io
  resources:
  - pipelines
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflows-executor
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflowtaskresults
  verbs:
  - get
  - list
  - watch
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflow-pods
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
