apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user-workflows
subjects:
- kind: ServiceAccount
  name: ${SERVICE_ACCT}
  namespace: ${NAMESPACE}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflows-executor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflows-executor
subjects:
- kind: ServiceAccount
  name: ${SERVICE_ACCT}
  namespace: ${NAMESPACE}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-secrets
subjects:
- kind: ServiceAccount
  name: argo
  namespace: argo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow
subjects:
- kind: ServiceAccount
  name: ${SERVICE_ACCT}
  namespace: ${NAMESPACE}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-agent
subjects:
- kind: ServiceAccount
  name: ${SERVICE_ACCT}
  namespace: ${NAMESPACE}
