---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-secrets
subjects:
- kind: ServiceAccount
  name: argo
  namespace: argo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workflow-agent
subjects:
- kind: ServiceAccount
  name: ${SERVICE_ACCT}
  namespace: ${NAMESPACE}
