apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: user-workflows
subjects:
- kind: ServiceAccount
  name: ${SERVICE_ACCT}
  namespace: ${NAMESPACE}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflows-executor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workflows-executor
subjects:
- kind: ServiceAccount
  name: ${SERVICE_ACCT}
  namespace: ${NAMESPACE}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workflow-pods
subjects:
- kind: ServiceAccount
  name: ${SERVICE_ACCT}
  namespace: ${NAMESPACE}
