apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ramin
  # namespace: argo-samples # Leaving out namespace so you'll need to use -n <namespace> when you apply
rules:
- apiGroups:
  - argoproj.io
  - dataflow.argoproj.io
  resources:
  - cronworkflows
  - eventsources
  - pipelines
  - sensors
  - workfloweventbindings
  - workflows
  - workflowtasksets
  - workflowtemplates
  verbs:
  - get
  - list
  - update
  - watch
  - create
  - patch
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executor
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - patch