controller:
  ## Events controller metrics configuration
  metrics:
    # -- Deploy metrics service
    enabled: true

## Argo Events admission webhook
# More info: https://argoproj.github.io/argo-events/validating-admission-webhook/
webhook:
  # -- Enable admission webhook. Applies only for cluster-wide installation
  enabled: true